export const liveCommerceFixture = {
  title: "科研立项引导助手流程验证 Demo",
  scenario: "小白老师从“AI+教育”收敛到直播电商实训教学改革课题",
  boundary:
    "本页面只验证流程、判断和产物结构；正式版本将在成熟 Harness 中运行科研立项 Skill。",
  gradeInput: {
    teacherProfileConfirmed: true,
    realProblemConfirmed: true,
    topicConfirmed: true,
    researchQuestionConfirmed: true,
    methodExecutable: true,
    nonPaperOutcomeConfirmed: true,
    guideSource: "demo_fixture",
    templateSource: "missing",
  },
  facts: {
    teacher: {
      value: "李老师，管理与数字经济学院网络营销与直播电商专业专任教师",
      sourceType: "user_confirmed",
      sourceLabel: "演示对话中由教师确认",
    },
    courses: {
      value: "新媒体直播运营、网店运营与管理、文案创意与撰写",
      sourceType: "user_confirmed",
      sourceLabel: "演示对话中由教师确认",
    },
    officialMajor: {
      value: "学校官网列示专业为“网络营销与直播电商”，所属管理与数字经济学院。",
      sourceType: "material_verified",
      sourceLabel:
        "四川国际标榜职业学院官网，网络营销与直播电商专业页，访问日期：2026-08-16",
    },
    officialPractice: {
      value:
        "官网介绍该专业强调实践性、技术性、多元性，课程体系与行业产业需求紧密结合，并配备直播实训室、摄影实训室、营销实训室以及综合直播基地。",
      sourceType: "material_verified",
      sourceLabel:
        "四川国际标榜职业学院官网，网络营销与直播电商专业页，访问日期：2026-08-16",
    },
    realProblem: {
      value:
        "学生能模仿直播话术，但选品、人群分析、脚本策划和数据复盘能力不足；课堂实训与企业直播运营岗位任务衔接不够。",
      sourceType: "user_confirmed",
      sourceLabel: "演示对话中由教师确认",
    },
    topicName: {
      value: "岗位任务导向的直播电商实训教学改革研究",
      sourceType: "ai_suggestion",
      sourceLabel: "系统基于教师画像、真实问题和演示指南生成，需教师最终采纳",
    },
    researchQuestion: {
      value:
        "在专科网络营销与直播电商专业的新媒体直播运营课程中，如何基于企业真实直播运营岗位任务重构实训项目，并通过数据复盘评价量表提升学生直播策划、执行和复盘能力？",
      sourceType: "user_confirmed",
      sourceLabel: "系统草拟后由教师确认",
    },
    evidence: {
      value:
        "模拟指南鼓励职业教育教学改革、产教融合、课程资源建设、评价工具和岗位能力提升。",
      sourceType: "demo_fixture",
      sourceLabel: "演示占位指南，不代表学校真实申报文件",
    },
    literatureFrontier: {
      value:
        "演示性前沿研究摘要：直播电商教学研究通常关注产教融合任务转化、数据化运营能力培养、课堂实训评价和 AI 辅助内容诊断。",
      sourceType: "demo_fixture",
      sourceLabel: "演示占位文献摘要；正式版本必须由真实检索结果生成",
    },
    template: {
      value: "学校真实申报书模板尚未提供。",
      sourceType: "missing",
      sourceLabel: "第二版真实材料 Demo 前需由科研处提供",
    },
  },
  topicOptions: [
    {
      title: "岗位任务导向的直播电商实训教学改革研究",
      reason: "覆盖岗位任务、实训流程、评价工具和可复用成果。",
      risk: "企业直播项目案例和真实模板仍需补充。",
      selected: true,
    },
    {
      title: "基于数据复盘的直播运营实训评价体系构建研究",
      reason: "聚焦学生不会分析直播过程数据的问题。",
      risk: "范围较窄，需证明对课程整体改革的带动作用。",
      selected: false,
    },
    {
      title: "AI 辅助下直播脚本诊断与优化的教学应用研究",
      reason: "保留 AI 工具价值，适合脚本质量提升。",
      risk: "容易被误解为工具应用课题，申报价值需要收敛。",
      selected: false,
    },
  ],
  dialogueSteps: [
    {
      stage: "教师画像采集",
      stateId: "teacher_profile",
      speaker: "teacher",
      text:
        "我是网络营销与直播电商专业老师，主要教新媒体直播运营和网店运营与管理。我想做一个 AI+教育 的课题，帮我写个课题申报。",
      note: "已获得教师画像和初始意图，但真实工作问题、课题方向和研究问题尚未建立。",
      visibleFactKeys: ["teacher", "courses", "officialMajor", "officialPractice"],
      gradeInput: {
        teacherProfileConfirmed: true,
        realProblemConfirmed: false,
        topicConfirmed: false,
        researchQuestionConfirmed: false,
        methodExecutable: false,
        nonPaperOutcomeConfirmed: false,
        guideSource: "missing",
        literatureSource: "missing",
        templateSource: "missing",
      },
    },
    {
      stage: "空泛意图纠偏",
      stateId: "intent_refinement",
      speaker: "assistant",
      text:
        "这个方向现在还不能直接生成申报材料。“AI+教育”太宽泛，我需要先确认专业、课程、学生问题和可获得数据。",
      note: "允许输出：继续追问，不生成申报材料。",
      visibleFactKeys: ["teacher", "courses", "officialMajor", "officialPractice"],
      gradeInput: {
        teacherProfileConfirmed: true,
        realProblemConfirmed: false,
        topicConfirmed: false,
        researchQuestionConfirmed: false,
        methodExecutable: false,
        nonPaperOutcomeConfirmed: false,
        guideSource: "missing",
        literatureSource: "missing",
        templateSource: "missing",
      },
    },
    {
      stage: "工作问题挖掘",
      stateId: "problem_discovery",
      speaker: "teacher",
      text:
        "学生会模仿直播话术，但真正做直播任务时，选品、人群分析、脚本策划和数据复盘都比较弱。",
      note: "真实问题开始形成，但还需要确认其是否是课题核心。",
      visibleFactKeys: ["teacher", "courses", "officialMajor", "officialPractice", "realProblem"],
      gradeInput: {
        teacherProfileConfirmed: true,
        realProblemConfirmed: false,
        topicConfirmed: false,
        researchQuestionConfirmed: false,
        methodExecutable: false,
        nonPaperOutcomeConfirmed: false,
        guideSource: "missing",
        literatureSource: "missing",
        templateSource: "missing",
      },
    },
    {
      stage: "工作问题挖掘",
      stateId: "problem_discovery",
      speaker: "assistant",
      text:
        "核心问题可能不是 AI 工具，而是直播电商岗位任务和课程实训没有充分对齐。请确认是否更想解决直播全流程能力问题。",
      note: "AI 建议需用户确认，不能替代教师判断。",
      visibleFactKeys: ["teacher", "courses", "officialMajor", "officialPractice", "realProblem"],
      gradeInput: {
        teacherProfileConfirmed: true,
        realProblemConfirmed: false,
        topicConfirmed: false,
        researchQuestionConfirmed: false,
        methodExecutable: false,
        nonPaperOutcomeConfirmed: false,
        guideSource: "missing",
        literatureSource: "missing",
        templateSource: "missing",
      },
    },
    {
      stage: "工作问题挖掘",
      stateId: "problem_discovery",
      speaker: "teacher",
      text: "认可。我最想解决的是学生不会把直播任务做完整，不是单纯上 AI 工具。",
      note: "真实问题由用户确认。",
      visibleFactKeys: ["teacher", "courses", "officialMajor", "officialPractice", "realProblem"],
      gradeInput: {
        teacherProfileConfirmed: true,
        realProblemConfirmed: true,
        topicConfirmed: false,
        researchQuestionConfirmed: false,
        methodExecutable: false,
        nonPaperOutcomeConfirmed: false,
        guideSource: "missing",
        literatureSource: "missing",
        templateSource: "missing",
      },
    },
    {
      stage: "课题方向推荐与确认",
      stateId: "topic_recommendation",
      speaker: "assistant",
      text:
        "结合教师画像、真实问题和演示性前沿研究摘要，我建议 3 个方向：岗位任务导向实训改革、数据复盘评价体系、AI 辅助脚本诊断。我推荐第 1 个，因为它覆盖实训流程、评价工具和可复用成果。",
      note: "系统推荐方向，等待用户选择；仍不生成申报材料。",
      visibleFactKeys: ["teacher", "courses", "officialMajor", "officialPractice", "realProblem", "topicName"],
      gradeInput: {
        teacherProfileConfirmed: true,
        realProblemConfirmed: true,
        topicConfirmed: false,
        researchQuestionConfirmed: false,
        methodExecutable: false,
        nonPaperOutcomeConfirmed: false,
        guideSource: "missing",
        literatureSource: "missing",
        templateSource: "missing",
      },
    },
    {
      stage: "课题方向推荐与确认",
      stateId: "topic_confirmation",
      speaker: "teacher",
      text: "我选第 1 个。这个方向确实来自我的课程实训问题。",
      note: "课题方向由用户确认，但研究问题还没有形成。",
      visibleFactKeys: ["teacher", "courses", "officialMajor", "officialPractice", "realProblem", "topicName"],
      gradeInput: {
        teacherProfileConfirmed: true,
        realProblemConfirmed: true,
        topicConfirmed: true,
        researchQuestionConfirmed: false,
        methodExecutable: false,
        nonPaperOutcomeConfirmed: false,
        guideSource: "missing",
        literatureSource: "missing",
        templateSource: "missing",
      },
    },
    {
      stage: "研究问题澄清",
      stateId: "research_question",
      speaker: "assistant",
      text:
        "研究问题可草拟为：如何基于企业真实直播运营岗位任务重构实训项目，并通过数据复盘评价量表提升学生直播策划、执行和复盘能力？请确认是否符合您的真实想法。",
      note: "研究问题仍是系统草案，等待用户确认。",
      visibleFactKeys: [
        "teacher",
        "courses",
        "officialMajor",
        "officialPractice",
        "realProblem",
        "topicName",
        "researchQuestion",
      ],
      gradeInput: {
        teacherProfileConfirmed: true,
        realProblemConfirmed: true,
        topicConfirmed: true,
        researchQuestionConfirmed: false,
        methodExecutable: false,
        nonPaperOutcomeConfirmed: false,
        guideSource: "missing",
        literatureSource: "missing",
        templateSource: "missing",
      },
    },
    {
      stage: "研究问题澄清",
      stateId: "research_question",
      speaker: "teacher",
      text: "符合。最好突出直播策划、执行、复盘的全流程能力。",
      note: "研究问题由用户确认，核心课题方案建立，质量等级开始进入 B。",
      visibleFactKeys: [
        "teacher",
        "courses",
        "officialMajor",
        "officialPractice",
        "realProblem",
        "topicName",
        "researchQuestion",
      ],
      gradeInput: {
        teacherProfileConfirmed: true,
        realProblemConfirmed: true,
        topicConfirmed: true,
        researchQuestionConfirmed: true,
        methodExecutable: false,
        nonPaperOutcomeConfirmed: false,
        guideSource: "missing",
        literatureSource: "missing",
        templateSource: "missing",
      },
    },
    {
      stage: "文献与政策支撑",
      stateId: "evidence_support",
      speaker: "assistant",
      text:
        "当前用模拟申报指南和演示性文献检索摘要演示：若强调产教融合、前沿研究缺口、课程资源、评价工具和岗位能力，比泛泛写 AI+教育更贴近申报导向。",
      note: "依据为 demo_fixture，不能视为真实材料。",
      visibleFactKeys: [
        "teacher",
        "courses",
        "officialMajor",
        "officialPractice",
        "realProblem",
        "topicName",
        "researchQuestion",
        "evidence",
        "literatureFrontier",
      ],
      gradeInput: {
        teacherProfileConfirmed: true,
        realProblemConfirmed: true,
        topicConfirmed: true,
        researchQuestionConfirmed: true,
        methodExecutable: false,
        nonPaperOutcomeConfirmed: false,
        guideSource: "demo_fixture",
        literatureSource: "demo_fixture",
        templateSource: "missing",
      },
    },
    {
      stage: "方法与成果设计",
      stateId: "method_and_outcomes",
      speaker: "teacher",
      text:
        "企业案例、课程试点、学生作业和直播数据截图可以配合。成果可以做任务包、评价量表、复盘模板和案例库。",
      note: "方法资源和非论文成果由用户确认，但真实指南和学校模板仍缺失。",
      visibleFactKeys: [
        "teacher",
        "courses",
        "officialMajor",
        "officialPractice",
        "realProblem",
        "topicName",
        "researchQuestion",
        "evidence",
        "literatureFrontier",
        "template",
      ],
      gradeInput: {
        teacherProfileConfirmed: true,
        realProblemConfirmed: true,
        topicConfirmed: true,
        researchQuestionConfirmed: true,
        methodExecutable: true,
        nonPaperOutcomeConfirmed: true,
        guideSource: "demo_fixture",
        literatureSource: "demo_fixture",
        templateSource: "missing",
      },
    },
    {
      stage: "申报材料生成与质检",
      stateId: "quality_checking",
      speaker: "assistant",
      text:
        "当前质量等级为 B：可生成课题方案卡、文献综述草稿、申报书字段映射稿、待补充清单和质量结果；不生成正式申报书草稿。",
      note: "缺少真实申报指南、真实文献检索结果和学校模板。",
      visibleFactKeys: [
        "teacher",
        "courses",
        "officialMajor",
        "officialPractice",
        "realProblem",
        "topicName",
        "researchQuestion",
        "evidence",
        "literatureFrontier",
        "template",
      ],
      showOutputs: true,
      gradeInput: {
        teacherProfileConfirmed: true,
        realProblemConfirmed: true,
        topicConfirmed: true,
        researchQuestionConfirmed: true,
        methodExecutable: true,
        nonPaperOutcomeConfirmed: true,
        guideSource: "demo_fixture",
        literatureSource: "demo_fixture",
        templateSource: "missing",
      },
    },
  ],
};
